services:
  feedback-service:
    container_name: feedback-service
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-pthaiit210501}/utctss-mss:v1
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - feedback-postgres
    environment:
      SERVICE_NAME: feedback
      DB_HOST: feedback-postgres
      DB_NAME: feedback
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - 5006:8080
    networks:
      - feedback-network
      - feedback-postgres-network
    volumes:
      - feedback-data:/app/storage

  feedback-postgres:
    container_name: feedback-postgres
    image: postgres:alpine3.19
    restart: unless-stopped
    volumes:
      - feedback-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: feedback
    ports:
      - 54326:5432
    networks:
      - feedback-postgres-network


  hermes-service:
    container_name: hermes-service
    env_file:
      - .env
    image: ${DOCKERHUB_USERNAME:-pthaiit210501}/utctss-mss:v1
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - hermes-postgres
    environment:
      SERVICE_NAME: hermes
      DB_HOST: hermes-postgres
      DB_NAME: hermes
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - 5003:8080
    networks:
      - hermes-network
      - hermes-postgres-network
    volumes:
      - hermes-data:/app/storage

  hermes-postgres:
    container_name: hermes-postgres
    image: postgres:alpine3.19
    restart: unless-stopped
    volumes:
      - hermes-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: hermes
    ports:
      - 54324:5432
    networks:
      - hermes-postgres-network

  adminer:
    container_name: adminer-postgres
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - feedback-postgres
      - hermes-postgres
    networks:
      - feedback-postgres-network
      - hermes-postgres-network

networks:
  feedback-postgres-network:
    name: feedback-postgres-network
    driver: bridge
  feedback-network:
    name: feedback-network
    driver: bridge

  hermes-postgres-network:
    name: hermes-postgres-network
    driver: bridge
  hermes-network:
    name: hermes-network
    driver: bridge

volumes:
  feedback-postgres-data:
    name: feedback-postgres-data
  feedback-data:
    name: feedback-data

  hermes-postgres-data:
    name: hermes-postgres-data
  hermes-data:
    name: hermes-data