services:
  server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-local
    #      target: final
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - education-supporting-system_mariadb-network

networks:
  education-supporting-system_mariadb-network:
    external: true

