# syntax=docker/dockerfile:1
FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./build/migrationtool ./database/migrations/tool/.
RUN CGO_ENABLED=0 GOOS=linux go build -o ./build/main ./app/.

ENTRYPOINT ["./build/main"]