FROM golang:1.22-alpine3.20

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download
RUN go install github.com/go-swagger/go-swagger/cmd/swagger@v0.31.0

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/migration-tool ./core/database/migrations/tool/main/.
RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/main ./app/.

#RUN addgroup -g 1000 appgroup
#RUN adduser -D -u 1000 appuser -G appgroup
#USER appuser

ENTRYPOINT ["./build/main"]