FROM golang:1.22-alpine3.20

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download
RUN go install github.com/air-verse/air@v1.52.2
RUN go install github.com/go-delve/delve/cmd/dlv@v1.22.1

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./core/database/migrations/tool/bin/migration-tool ./core/database/migrations/tool/main/.

CMD ["air", "-d"]
