# syntax=docker/dockerfile:1
FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o ./build/migrationtool ./database/migrations/tool/.
RUN CGO_ENABLED=0 GOOS=linux go build -o ./build/main ./app/.

#RUN addgroup -g 1000 appgroup
#RUN adduser -D -u 1000 appuser -G appgroup
#USER appuser

ENTRYPOINT ["./build/main"]