# syntax=docker/dockerfile:1
FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/air-verse/air@v1.52.2
RUN go install github.com/go-delve/delve/cmd/dlv@v1.22.1
COPY . .

RUN #go test -v ./...

#RUN addgroup -g 1000 appgroup
#RUN adduser -D -u 1000 appuser -G appgroup

#USER appuser
CMD ["air", "-d"]
